//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Relative_Space_Controls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.relative_Space_Controls_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.relative_Space_Controls_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnLeft
        {
            get
            {
                return SteamVR_Actions.relative_Space_Controls_TurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnRight
        {
            get
            {
                return SteamVR_Actions.relative_Space_Controls_TurnRight;
            }
        }
    }
}
